### ISSUE TITLE
Registering a CWL results in a weird error message

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [ga4gh/dockstore#335] opened 2016-07-14 19:24 UTC
I got this error message:

" Fields that are missing from file: [] "

When I registered a tool based on this CWL:
https://github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/blob/896c090590443379bd2184344835ef505b23f8d7/clean_vcf.cwl

This happened in the staging environment.

**Comment by denis-yuen** [comment] 2016-07-22 14:53
@jpatricia

**Comment by jpatricia** [comment] 2016-07-22 15:01
I could not reproduce the issue, as the file itself is not missing anything, but there was a problem with refreshing the page as the file is being copied and edited to a new Tool. After refreshing the tool and the page, the warning is gone, and it was not supposed to be there from the beginning since the file is correct.

**Comment by denis-yuen** [comment] 2016-09-16 18:15
Just saw this again "Fields that are missing from file: []"
Also, grammar, should be something like "Warning: there are fields missing from the descriptor: [cwlVersion]"

**Comment by denis-yuen** [comment] 2016-11-23 22:43
This looks completely fixed as of 1.1

**Closed by denis-yuen** 2016-11-23 22:43 UTC
Labels: bug, gui
