### ISSUE TITLE
ui2 sync node version in travis testing with compose setup

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2264] opened 2019-03-21 16:14 UTC
### Desired behaviour

It seems that ui2 travis tests may be testing a different version of node than our deployment. 
Please downgrade and test the deployment version temporarily.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-606)
┆Issue Type: Story
┆Issue Number: DOCK-606

**Comment by garyluu** [comment] 2019-03-21 16:31
Node version can be downgraded in a separate branch that never gets merged... but it's a mystery how Travis gets a global `@angular/cli` without installing one

**Comment by coverbeck** [comment] 2019-03-21 16:42
There's a way to install and run Angular CLI non-globally. I think we should ideally do that, as today there is no guarantee that all of us are running the same Angular CLI locally.

Definitely post 1.6 though.

**Comment by garyluu** [comment] 2019-03-21 16:44
Oh, we're installing it non-globally.  The problem is that we need a global version (pretty much any version) to run ng commands (which the local one then overrides)

**Comment by coverbeck** [comment] 2019-03-21 16:47
I think you can do it without even the global version: https://medium.com/@starikovs/how-to-use-angular-cli-locally-729dbb6707dd

**Comment by garyluu** [comment] 2019-03-21 16:48
Yes, now we run into the problem of install npx globally :)

**Comment by coverbeck** [comment] 2019-03-21 16:52
Isn't npx part of npm, and we already are installing that globally.

But, good point about needing to change all the commands.

And if global Angular CLI is using the local Angular CLI version anyway, which I didn't realize, then never mind. :)

**Comment by garyluu** [comment] 2019-03-21 16:59
npx is only parts of certain npm versions, no idea which ones.  The global CLI uses the local CLI is most versions I can think of, but there's no guarantee

**Comment by garyluu** [comment] 2019-03-25 18:21
be3c0478800dafbc0fb7a074d329338cc4bf240a to be reverted

**Comment by garyluu** [comment] 2019-03-25 18:22
Does this even need to be "tested" or should we just change this issue to something that reminds us to revert it later.

**Comment by denis-yuen** [comment] 2019-03-25 18:32
> Does this even need to be "tested" or should we just change this issue to something that reminds us to revert it later.

Doesn't really need review. Create a new issue for 1.7.0 to revert these

**Comment by garyluu** [comment] 2019-03-25 18:38
https://github.com/ga4gh/dockstore/issues/2279

**Closed by garyluu** 2019-03-25 18:38 UTC
Labels: gui
