### ISSUE TITLE
TagEditor's Dockerfile folder and extension

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#772] opened 2017-06-14 15:48 UTC
### Expected behaviour
Dockerfile's form validation error message to be correct.

### Actual behaviour
Dockerfile's form validation error message is not clear/correct.  A pattern like:
/test/Dockerfile.test should be allowed but it is not

### Steps to reproduce the behaviour 
- Go to tool tag editor
- Edit a tag's Dockerfile to be /test/Dockerfile.test
- Observe the error that appears.

### Environment (Browser or OS and Dockstore version)
UI2

**Comment by denis-yuen** [comment] 2017-07-12 17:45
FYI, this is actually reversed. 
`/test/test.Dockerfile` should be allowed, not `/test/Dockerfile.test`

**Comment by denis-yuen** [comment] 2017-07-14 16:22
NVM, duplicate of #823

**Closed by denis-yuen** 2017-07-14 16:22 UTC
Labels: gui2
