### ISSUE TITLE
Creating hosted entry API returns 200 instead of 201

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1859] opened 2018-10-11 00:03 UTC
## Bug Report

The API to create a hosted workflow returns a 200 status code. It should be a 201.

### Steps to reproduce the behaviour 

1. Open Developer Tools in your browser
2. Go to My Workflows
3. Create a hosted workflow in the UI
4. Note that the POST call to create the workflow returns 200 instead of 201.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-118)
┆Issue Number: DOCK-118

**Comment by cricketsloan** [comment] 2018-11-08 03:12
➤ Walt Shands commented:

The Dockstore team felt that the decrease in readability in the PR that addressed this bug report outweighed the benefit of conforming more closely to REST principles, and suggested closing the PR but keeping the ticket open in case a better way of resolving the issue is found.

**Closed** 2019-02-15 17:38 UTC
Labels: web service
