### ISSUE TITLE
Test absolute path migrations

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#2221] opened 2019-03-13 12:26 UTC
Test the following (and maybe more)
> * Refreshing of existing workflows, migrated with the new paths
> * launching old workflows both before and after refresh (with cwltool pointing at TRS)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-581)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-581

**Comment by denis-yuen** [comment] 2019-03-26 19:23
* existing workflows
* do they work 1) before refresh 2) after refresh in the GUI
* same thing for launching via CLI
* pick workflows that look like they have an odd path structure

**Comment by denis-yuen** [comment] 2019-03-26 19:25
Watch out for #2255

**Comment by agduncan94** [comment] 2019-03-27 17:18
Putting my findings into this comment.
-NF core workflows seem to work with just the basic migrations, refresh not needed

**Comment by garyluu** [comment] 2019-03-27 18:33
Tooltester runs everything fine as expected (/var/cwl/spool problems still present from before)

**Comment by denis-yuen** [comment] 2019-03-27 19:10
Might be worth verifying the new releases that have been made, ping @junjun-zhang if you have difficulty identifying appropriate versions. I think all pcawg workflows minus bwa-mem should have fixed versions for the /var/cwl/spool issue

**Comment by denis-yuen** [comment] 2019-03-29 14:44
@garyluu oh I see, testing for pcawg workflows can be a new 1.6.X ticket if you're comfortable with the new path code in terms of before/after refresh for existing workflows

**Comment by garyluu** [comment] 2019-03-29 19:02
Not sure if relevant but...

![image](https://user-images.githubusercontent.com/24548904/55256531-9a79e400-5233-11e9-87ee-22842cee2e05.png)

Shows paths with `../` in it when my repo looks like:
https://github.com/garyluu/one-workflow-many-ways/tree/master/cwl

**Comment by denis-yuen** [comment] 2019-03-29 19:08
Looks like it, please find out how widespread the issue is and whether it affects download/execution

**Comment by garyluu** [comment] 2019-03-29 19:41
Affects download and execution

**Comment by denis-yuen** [comment] 2019-03-29 19:56
after/before refresh? 
can you tell which of the absolute path commits caused this issue?

**Comment by garyluu** [comment] 2019-03-29 20:31
before refresh, absolute path looks fine in DB though

**Comment by denis-yuen** [comment] 2019-03-29 21:44
For Monday, newest issue boils down to this guess being poor 
https://github.com/ga4gh/dockstore/blob/develop/dockstore-webservice/src/main/resources/migrations.1.6.0.xml#L343

And breaking places that depend on it being correct like https://github.com/ga4gh/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/EntryVersionHelper.java#L341 and https://github.com/ga4gh/dockstore/blob/develop/dockstore-webservice/src/main/java/io/swagger/api/impl/ToolsApiServiceImpl.java#L574

Probably https://github.com/ga4gh/dockstore/blob/develop/dockstore-webservice/src/main/java/io/swagger/api/impl/ToolsApiServiceImpl.java#L716 too

**Comment by denis-yuen** [comment] 2019-03-29 22:16
Options 
1) Don't guess absolute path, but all code that uses absolute paths now need to work out absolute path if not present
2) Calculate absolute paths correctly during migration
3) Refresh workflows without absolute paths to get absolute paths

**Comment by garyluu** [comment] 2019-04-01 15:24
3. I added myself as another user of the workflow (user_entry table).  Refreshed the workflow (http://10.11.8.92.nip.io:4200/my-workflows/github.com/HumanCellAtlas/skylab/HCA_SmartSeq2). It still has the same problem.

**Comment by denis-yuen** [comment] 2019-04-01 16:47
@garyluu mentioned that refresh doesn't seem to be working properly with workflows in this state

**Comment by denis-yuen** [comment] 2019-04-05 18:22
Last issue seems fixed with https://github.com/ga4gh/dockstore/pull/2334/commits/ed504a999bf20b7bc3c1c71e13d9ee51ac18e323

**Comment by denis-yuen** [comment] 2019-04-05 18:23
Reopen with more targeted issues if need be

**Closed by denis-yuen** 2019-04-05 18:23 UTC
Labels: gui, web-service
