### ISSUE TITLE
feature/read-extension-when-register-workflow

### ISSUE THREAD

**Issue by mjkrause** [ga4gh/dockstore#1391] opened 2018-05-04 18:12 UTC
## Feature Request
When a user registers a new workflow s/he inputs the workflow path (see below). It happened to me that I entered a WDL workflow with extension `.wdl`. When I tried to register it it threw an error. The reason was I had not set the pull-down to the left to `wdl`.
![image](https://user-images.githubusercontent.com/15079157/39643475-bca341c8-4f89-11e8-974b-b615fe494766.png)

### Desired behaviour
If a user inputs a new workflow path (with extension) it would be nice if the pull down to the left of it would set automatically to the appropriate extension. If the code could read the extension of the workflow path, then set the pulldown value accordingly that would be awesome.

### Environment (Browser or OS and Dockstore version)
I experienced what I described above on the Dockstore website (Ubuntu 16, latest Chrome).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-340)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-340

**Comment by denis-yuen** [comment] 2018-07-13 15:38
While testing this, I also noticed that pressing enter will close the dialogue even when validation is incorrect.

**Comment by garyluu** [comment] 2018-07-23 14:42
wasn't implemented because didn't want to assume the extension since it can be yaml, yml, .config, .nextflow  .

**Comment by denis-yuen** [comment] 2018-07-23 14:46
Ah, then it probably shouldn't have been moved over to ready for testing. 
I think you can do the non-ambiguous ones, cwl, wdl, config don't overlap yet. 
You can ignore yaml, wml for now

**Comment by garyluu** [comment] 2018-07-23 14:49
my PR actually mentions this, thought everyone was ok with it.  but if you're certain this is more useful than the problems it may cause, i can implement it

**Comment by denis-yuen** [comment] 2018-07-23 14:59
Sorry, I must have missed that. Re-reading, the PR seemed to bury the lead.
In general, if implementing something that's helpful, but doesn't quite address the issue at hand, I'd prefer to leave the ticket open for discussion. 

For the specific issue, can you elaborate on what problems you foresee?

**Comment by garyluu** [comment] 2018-07-23 15:34
i generally find modifying form elements for the user takes away control from them and can go horribly wrong when not implemented perfectly.  

For example, i can name my CWL descriptor file to be /Dockstore.wdl.cwl (for whatever reason) and even though it may be a completely strange file name, the form would automatically switch to a WDL extension as I am typing and it would be annoying and i might not even notice it.  

In my opinion, it should flow one way.  User actions on form control => validation and that's it.  Depending on what auto-modifying on the user's behalf, it might end up with an infinitely loop of:
User actions on form control => validation => auto-modify => validation => auto-modify => etc.

Another slightly unrelated example of taking control from the user is in UI1 when we automatically cleared the input field and used a placeholder when we changed descriptor type even though what I entered in previously was what I wanted.  It was intended to help save the user time, but ended up silently changing it and I would register without noticing it.  Then I would wonder why nothing shows up in the file tab.

Overall, I would tread carefully when deciding whether to implement something like this, especially when the extension => descriptor type is not completely clearcut (yaml, yml)

**Comment by denis-yuen** [comment] 2018-07-23 15:43
Thanks, I think I'm convinced when the descriptor type is not completely clearcut (yaml, yml). Let's set those aside. 

I'm not sure the `/Dockstore.wdl.cwl` example would be a problem though, since it would switch to WDL when the user has typed `/Dockstore.wdl` but it should switch back to CWL after they get to `/Dockstore.wdl.cwl`. It would be a great test though. 

I do appreciate the point that this could take more thought to work out the various cases. Please spend some time working out a few cases (on paper if it helps?) and seeing if there is a conservative solution that can still nonetheless make it easier for most users. Thanks!

**Comment by garyluu** [comment] 2018-07-23 15:48
/Dockstore.wdl.cwl would annoyingly double-swap, /Dockstore.wdl.yaml or /Dockstore.wdl.yml would outright not work though.

**Comment by david4096** [comment] 2019-03-04 18:08
Another option might be to offer a dialog that says, "Is this a WDL file?" when the filename detection occurs. Then clicking a button sets the extension metadata. I tend to agree with Gary that making selections on behalf of the person filling out the form can lead to confusion, but hints might be a nice compromise. That way when it "swaps" its swapping the hint, and not a value. The person registering the workflow can ignore the hints.

Alternatively, one might expect this feature to work with a backend service that performs the file validation (or introspection). That way, when someone enters a path to a file, it would have to be retrieved from the source repo and validated during this flow.

**Comment by garyluu** [comment] 2019-03-04 18:37
A few things have changed since the initial discussion. 

To me, I think the main pain points of the original design was:
- the descriptor type dropdown was not noticeable enough
- there was no descriptor type specific validation
- people might fill in the filename first and validation won't catch it, no errors would be thrown which allowed the user to click register workflow

Currently:
- Descriptor type is a simple and important question that is clearly before the filename field (no way the user is going to miss it)
- Validation on the filename is now specific to the descriptor type and displays and error if there is one
- If validation failed, the register workflow button would not be enabled

Overall, I think the changes made since then have rendered this issue irrelevant.

**Comment by david4096** [comment] 2019-03-04 18:49
Thanks @garyluu I commented before realizing I was assigned to verify the current status!

**Comment by cricketsloan** [comment] 2019-03-05 07:23
➤ David Steinberg commented:

I can confirm that this process is improved from when the issue was originally posted, and although the feature is not exactly what is requested. I think it can be closed. Any further improvements to the behavior will require some design.

**Closed** 2019-03-05 15:20 UTC
Labels: enhancement, gui
