### ISSUE TITLE
Dockstore CLI tool search shows unpublished tools

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1195] opened 2018-02-28 16:01 UTC
### Expected behaviour
`./dockstore tool search` should only show published tools
### Actual behaviour
`./dockstore tool search` also shows unpublished tools

### Steps to reproduce the behaviour 
- Use Dockstore client from 1.3.1 or 1.4.0-alpha.8 with develop's webservice loaded with UI2's travis/db_dump.sql
- `./dockstore tool search --pattern a`
Unpublished tools are listed.

**Comment by agduncan94** [comment] 2018-04-06 01:25
Should users be able to see their own unpublished tools in the search results?

Also is this an issue for workflows as well?

**Comment by denis-yuen** [comment] 2018-06-22 14:57
Agreement in discussion: listing should include a user's own unpublished, search should be public only just like in our UI search

**Comment by agduncan94** [comment] 2019-01-09 16:14
This seems to be fixed in 1.6.0-alpha.1-SNAPSHOT. I couldn't reproduce.

**Closed** 2019-01-10 05:03 UTC
Labels: bug, cli
