### ISSUE TITLE
Clicking on a label should search all tools/workflows for that label

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1427] opened 2018-05-18 14:30 UTC
I think this used to be a feature in the past, but now you cannot click on labels. Not sure if this was removed on purpose or by accident during migration to angular 4 or something.

**Comment by denis-yuen** [comment] 2018-06-19 15:36
Duplicate of #1197

**Closed by denis-yuen** 2018-06-19 15:36 UTC
Labels: enhancement, gui2
