### ISSUE TITLE
Nextflow DAG display and tool tab display

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1398] opened 2018-05-08 15:39 UTC
### Desired behaviour

This one may be tricky to do without language bindings, but its worth a try to see if we can do something basic for now.  Follows #1041

**Comment by agduncan94** [comment] 2018-07-20 13:55
I'm at the point where I have the code properly connecting processes, but ONLY if no operations on the channels have been made.

Nextflow is not like other languages, you can do some extra stuff between tools within a workflow using [operations](https://www.nextflow.io/docs/latest/operator.html#) on channels. This is awesome from a user perspective, but parsing this can be a pain. Not only are there like 40 operations, but also you can chain them together.

Nextflow has a collection of high quality workflows found at http://nf-co.re/. Denis suggested that we implement operators that exist in these, so that we can show off what the DAG could be capable of.

**Comment by agduncan94** [comment] 2018-08-01 15:11
There seems to be a related issue of nextflow files not properly being added, will investigate.

**Comment by denis-yuen** [comment] 2018-08-24 21:12
Probably not the right place for this, but we need to disable the "Add Checker Workflow" button for Nextflow until we have an idea for how it will work

**Comment by agduncan94** [comment] 2018-09-04 13:11
Closing this as it is sort of a duplicate of https://github.com/ga4gh/dockstore/issues/1041

**Closed by agduncan94** 2018-09-04 13:11 UTC
Labels: enhancement, gui2, web service
