### ISSUE TITLE
Need to relax regular expression for Version Tags (also warning message hidden with quay.io tools)

### ISSUE THREAD

**Issue by wshands** [ga4gh/dockstore#776] opened 2017-06-15 16:37 UTC
## Feature Request 
I would like to register a tool on Dockstore where the image has been pushed to Quay.io not built on Quay.io. 
The image tag for the image that was pushed to Quay.io appears on Quay.io like this:
![screen shot 2017-06-15 at 9 02 18 am](https://user-images.githubusercontent.com/3650921/27190470-6757e054-51a9-11e7-8d4b-8fc9952bec4b.png)

And in Dockstore under quay.io/ucsc_cgl/rnaseq-cgl-pipeline the Quay.io tag appears as follows:
![screen shot 2017-06-15 at 8 53 47 am](https://user-images.githubusercontent.com/3650921/27190380-27431f24-51a9-11e7-91a9-185cd3b4b579.png)
Note that the text to the right of the radio button in the Git Reference column says 'n/a', which I assume means Dockstore cannot figure out the Github repo from which the image was created. Also the Valid column has an X indicating the image Tag cannot be used. If I try to fill out the information on the on the Edit Version Tag dialog I am unable to save the information.

Also if I select the radio button to set it as the default branch for that image with a Git Reference radio button that has text n/a the page refreshes and ignores the selection.

I also presume since Dockstore does not know what the Github repo is that is why the Save Changes button on the Edit Version Tag dialog never enables when I try to edit the version tag information:
![screen shot 2017-06-15 at 9 17 01 am](https://user-images.githubusercontent.com/3650921/27191090-918c0b28-51ab-11e7-8a76-845372a38e69.png)

### Desired behaviour
I would like to be able to successfully select a version of an image in Dockstore that has been pushed to Quay.io. Perhaps there could be a way to specify the Github repo on the Edit Version Tag dialog that would tell Dockstore where the source for the image was located.

### Steps to reproduce the behaviour 

(Attach tool/workflow documents or links where applicable to help us reproduce your issue)

**Comment by denis-yuen** [comment] 2017-06-15 17:24
Hi,
The "n/a" for a version means that since the image was pushed to Dockstore, we cannot determine which GitHub repo or what tag in that repo is associated with the image. However, since the image is on quay.io we managed to successfully harvest the version number "3.3.3--1.1.2". Experimenting in a different tool, the double dash trips up our regular expression for version numbers. 

Could you try "3.3.3-1.1.2" for the tag name on quay.io instead?


![screenshot from 2017-06-15 13-19-08](https://user-images.githubusercontent.com/1730679/27193582-528772f6-51cd-11e7-82d7-2aee41e8c271.png)

**Comment by wshands** [comment] 2017-06-15 18:14
Hi Denis, Yes, thanks the Save Changes button on the Edit Version Tag dialog enabled and I was able to save changes after I changed the Quay.io image tag to '3.3.3-1.12.3' (removed the extra hyphen). I will test and see if I can launch the tool with Dockstore. 

I also have a question about the descriptor file (CWL file) that we provide for the tool; in particular the requirements section:
requirements:
  - class: DockerRequirement
    dockerPull: "quay.io/ucsc_cgl/rnaseq-cgl-pipeline:3.2.1-1"

It currently has a tag (3.2.1-1) that it would seem we need to update to '3.3.3-1.12.3', however our build process automatically generates tags.  We have to update the tag in the rnaseq-cgl-pipeline.cwl file manually commit and push to Github. I don't know of an automated way to update the tag. Is there a way around this? I suppose this requirement section is vital for Dockstore?

**Comment by denis-yuen** [comment] 2017-06-15 18:24
The requirement section is used by cwltool actually to determine which Docker image version is run. 
It is awkward, but we haven't found a good solution for getting rid of this redundancy (since we as Dockstore have the information on which image version to use).

**Comment by coverbeck** [comment] 2017-12-22 17:35
@denis-yuen @agduncan94 I'm not clear what to verify here. This seems to overlap or duplicate #728 , which I have commented on. Is there anything else I should be checking here?

Is it something about the warning message with quay.io tools? I'm not clear on how to reproduce that.

Thanks.

**Comment by agduncan94** [comment] 2017-12-28 03:45
@coverbeck I don't think there is anything else to test that wouldn't also be tested by #728.

As for the warning message, I think it has been updated to reflect the new changes to the validation so just ensure that those messages make sense.

**Comment by coverbeck** [comment] 2018-01-02 18:39
@agduncan94, just to be sure I'm not missing something, I entered comments in #767 on validation messages' contents. Are you referring to those validation messages, or to something else? If those comments cover it, I'll close this one. Thanks.

**Comment by agduncan94** [comment] 2018-01-02 18:45
Yes those are the validation messages, so you can close this one.

**Closed** 2018-01-02 18:46 UTC
Labels: enhancement, gui2
