### ISSUE TITLE
Discrepancy in intake of wdl metadata between staging and production

### ISSUE THREAD

**Issue by Ldcabansay** [ga4gh/dockstore#1942] opened 2018-12-04 19:24 UTC
### Expected behaviour
In both staging and production, a wdl workflow should use the meta{} syntax in the [wdl file](https://github.com/Ldcabansay/expeditions/blob/master/u_of_michigan_aligner.wdl) to populate author, email, description, etc fields on the info tab of the workflow landing page. 
Example of syntax: `  meta {
          author : "Mr. Bar" 
          email : "foo@foo.com"
          description: "This is a cool workflow"`
### Actual behaviour
After registering a wdl workflow in staging.dockstore, the wdl meta{} syntax intake is not working. No author or email is displayed and description defaults to "No description associated with this workflow...".
The metadata is correctly pulled from the wdl in the production version of dockstore, with the exception of some markdown syntax used in the description field not displaying correctly. 

### Steps to reproduce the behaviour 

(Attach tool/workflow documents or links where applicable to help us reproduce your issue)

### Environment (Browser or OS and Dockstore version)
Production: Chrome- 70.0.3538.77, DockstoreAPI - 1.5.1, DockstoreUI - 2.2.2
Staging: Chrome- 70.0.3538.77, DockstoreAPI - 1.5.3DockstoreUI - 2.2.5

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-144)
┆Sprint: Lighthouse Sprint 40 Nob Hill
┆Issue Number: DOCK-144

**Comment by denis-yuen** [comment] 2018-12-04 21:13
FYI, I think I can duplicate part of the issue. 
With  I can get the author, email, and description https://staging.dockstore.org/workflows/github.com/denis-yuen/expeditions:v1.0?tab=info when the default is set to v1.0 but it doesn't work with v2.0.
It seems that the multi-line WDL description is breaking something silently. 

It seems to behave the same (broken with multi-line) with both except #1808 occurs a lot which is really annoying.

**Comment by Ldcabansay** [comment] 2018-12-04 21:54
Can confirm that on staging info tab now displays correctly when I update existing workflow to a one line description. Production finally updated correctly when I changed to a one line description too. For some reason production will display author and email even if the description is multi-line. So only the description breaks in production but it all breaks in staging.

**Comment by denis-yuen** [comment] 2018-12-04 22:29
It looks like the same parsing code for both and I can verify both die on the multi-line description with a `WdlParser.SyntaxError`. I think it can be counter-intuitive because it will currently only replace the email, author, and description with a valid entry. 

i.e. if you start with something valid, try to replace it with something invalid, it will keep displaying the old valid information. If you start with something invalid, it will never display anything. 
This is probably the wrong behaviour and we should probably blank the value and display an error message when trying to replace something valid with something invalid.

**Comment by coverbeck** [comment] 2018-12-06 23:52
Flow looks the same between in prod and staging. I think the difference in behavior is as @denis-yuen says -- if you switch to a version where the description is broken, then the previous value remains, whatever it was.

**Comment by agduncan94** [comment] 2018-12-07 16:37
If we can confirm what @coverbeck  is saying, we should change this to a feature request.
Here are some ideas:
1. When there is a validation error for the wdl workflow, we should blank author, email and description, showing that there is an error, prompting the user to fix the wdl. As opposed to showing the previous version of the author, email, and description. @Ldcabansay You may find the validation branch https://github.com/ga4gh/dockstore/pull/1853 useful for figuring out what the errors are going forward until it is merged.

1. Related to these two tickets #1943 #1642 (possibly more) we should distinguish between items related to the workflow as a whole vs each version. There is value in an author selecting a default version, however when a user navigates to a version they should be able to figure out what info is coming from where. Perhaps we can remove some clutter from the info tab, such as repository which is available on the side bar when published. Perhaps we show different information based on being in my tools vs tools.

**Comment by coverbeck** [comment] 2018-12-07 17:06
I should have been more definitive in my previous comment in stating the behavior is the same; I ran both versions in the debugger and the stack trace is the same in both cases.

I had been thinking of implementing part of step 1 -- clearing out the author, email, and description, if there is an error reading the WDL. However, given the other items you mention, not sure we should if it makes sense to do on its own. If we're going to change the the info tab to display the current version's description, author, and email, then I don't think we should add some workflow level flag to indicate whether the workflow is valid or not (which we would need to inform/prompt the users to fix their WDL).

@denis-yuen , should we just wait on the broader changes, or do you think it's worth making a fix for now to just clear out the author, email, and description if there is a syntax error in the WDL?

**Comment by denis-yuen** [comment] 2018-12-07 19:32
I think a hot fix to clear things out in case of error would be useful.
It would more ideal to also have the validation branch above to show users what the error actually is, but there is too much disruption to get that full branch into a hotfix. I'd like a low risk cut-down way of getting at least a warning message to the user if we proceed to clear things out.

**Comment by agduncan94** [comment] 2019-01-08 14:18
Confirmed that this is fixed.

**Closed by agduncan94** 2019-01-08 14:18 UTC
Labels: bug
