### ISSUE TITLE
Setting someone as admin won't instantly update their admin status in the web service or UI

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#481] opened 2016-11-10 14:41 UTC
To make someone admin we have to do a manual SQL update command. The UI caches our user information so we have to logout then login to apply the changes. The webservice also caches our user information, so we have to wait until the cache expires (see dockstore.yml) for the user to become an admin.

**Comment by denis-yuen** [comment] 2017-10-31 18:34
Looks like a duplicate of #472

**Closed by denis-yuen** 2017-10-31 18:34 UTC
Labels: bug, gui, web service
