### ISSUE TITLE
https://dockstore.org/docs/ produces a 403

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#815] opened 2017-07-09 18:04 UTC
## Bug Report

https://dockstore.org/docs/ produces a 403

### Expected behaviour

https://dockstore.org/docs/ should display the docs not a 403

The docs work fine if you go to https://dockstore.org/docs/documentation which redirects to https://dockstore.org/docs/.  But if you reload https://dockstore.org/docs/ directly you get the 403 which will cause problems for people bookmarking the link.

### Actual behaviour

https://dockstore.org/docs/ produces a 403

### Steps to reproduce the behaviour 

navigate to https://dockstore.org/docs/ and hard refresh your browser.

(Attach tool/workflow documents or links where applicable to help us reproduce your issue)

### Environment (Browser or OS and Dockstore version)
Chrome
DockstoreUI - 1.2.3-1-gd39f3b2
DockstoreApi - 1.2.3

**Comment by denis-yuen** [comment] 2017-07-09 21:46
FYI, this is a duplicate of #632

**Closed by denis-yuen** 2017-07-09 21:46 UTC
Labels: bug, gui
