### ISSUE TITLE
s3cmd plugin is very noisy for valid actions

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#790] opened 2017-06-27 13:24 UTC
## Bug Report

Uploads to S3 like system with s3cmd plugin gives lots messages indicating errors but files are fine.

### Expected behaviour

Should upload without claiming errors have occurred (warnings at worst, although I can't see what the issue is)

### Actual behaviour

```
Calling on plugin io.dockstore.provision.S3CmdPlugin$S3CmdProvision to provision from /tmp/wr_cmd/cwd/./datastore/launcher-acfd5a42-1ba9-4960-87eb-739006540a24/outputs/COLO-829.bam.md5 to s3cmd://wr-test/d053fd42-b720-4b6c-a7fc-3c1fdb8cb0ae/map/COLO-829.bam.md5
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!eCommon-known-issues-and-their-solutions
ERROR: Parameter problem: Expecting S3 URI with just the bucket name set instead of 'wr-test'
upload: '/tmp/wr_cmd/cwd/./datastore/launcher-acfd5a42-1ba9-4960-87eb-739006540a24/outputs/COLO-829.bam.md5' -> 's3://wr-test/d053fd42-b720-4b6c-a7fc-3c1fdb8cb0ae/map/COLO-829.bam.md5' (32 bytes in 0.1 seconds, 529.21 B/s) [1 of 1]
```

### Steps to reproduce the behaviour 

Specify a full s3 name (prefixed with `s3cmd://`)

### Environment (Browser or OS and Dockstore version)

Dockstore: 1.2.3
s3cmdplugin: 0.0.4

**Comment by denis-yuen** [comment] 2017-06-27 14:11
@garyluu  Maybe first give 0.0.5 that you created for https://github.com/dockstore/s3cmd-plugin/issues/1 a shot

**Comment by garyluu** [comment] 2017-06-28 16:55
Can't seem to reproduce with any version.  That error typically occurs when the bucket does not exist (or if the plugin can't find the bucket).  I'm going to log the s3cmd commands executed in 0.0.6 to assist in debugging issues like this.

**Comment by denis-yuen** [comment] 2017-12-21 15:57
Closing for now until we can reproduce this

**Comment by keiranmraine** [comment] 2018-01-02 09:46
FYI I found the likely cause of this is actually that `s3cmd info` doesn't work on rados/CEPH buckets, only on actual objects.  This appears to be a know issue due to the way that rados responds:

```
Invoked as: /Users/kr2/homebrew/Cellar/s3cmd/2.0.1/libexec/bin/s3cmd info s3://wr-test/
Problem: TypeError: cannot concatenate 'str' and 'NoneType' objects
S3cmd:   2.0.1
python:   2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
environment LANG=en_GB.UTF-8

Traceback (most recent call last):
  File "/Users/kr2/homebrew/Cellar/s3cmd/2.0.1/libexec/bin/s3cmd", line 3073, in <module>
    rc = main()
  File "/Users/kr2/homebrew/Cellar/s3cmd/2.0.1/libexec/bin/s3cmd", line 2989, in main
    rc = cmd_func(args)
  File "/Users/kr2/homebrew/Cellar/s3cmd/2.0.1/libexec/bin/s3cmd", line 939, in cmd_info
    expiration_desc += "objects with key prefix '" + expiration['prefix'] + "' "
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by denis-yuen** [comment] 2018-01-02 15:24
Yeah, I can confirm that we check that a bucket exists before uploading to it. 
https://github.com/dockstore/s3cmd-plugin/blob/develop/src/main/java/io/dockstore/provision/S3CmdPlugin.java#L161

**Comment by denis-yuen** [comment] 2018-01-02 15:26
@keiranmraine do you have a link to the issue on Github(?), maybe there's a workaround or maybe we can suppress the error message in this known condition

**Comment by keiranmraine** [comment] 2018-01-02 15:33
There are several causes on the ceph tracker:

http://tracker.ceph.com/issues/21901

http://tracker.ceph.com/issues/19448#note-2

**Comment by garyluu** [comment] 2018-01-04 22:12
I've been trying to reproduce this using cancercollab's ceph s3, but still can't reproduce it.  s3cmd info seems to work no matter what.  In the mean time, I've added a verbosity option to this plugin which controls the output display for each command.  The readme will explain in more detail what each level does.

**Comment by keiranmraine** [comment] 2018-01-05 09:07
@garyluu , could you get me the version of the Ceph and radosgw?  Would be interesting to see how they compare to our site systems.

FYI, the buckets I have were created using s3cmd and then used by s3cmd-plugin:

e.g.

```
$ s3cmd mb s3://test-bucket
Bucket 's3://test-bucket/' created
$ s3cmd info s3://test-bucket
s3://test-bucket/ (bucket):
   Location:  us-east-1
   Payer:     BucketOwner

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /Users/.../homebrew/Cellar/s3cmd/2.0.1/libexec/bin/s3cmd info s3://test-bucket
Problem: TypeError: cannot concatenate 'str' and 'NoneType' objects
S3cmd:   2.0.1
python:   2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
environment LANG=en_GB.UTF-8

Traceback (most recent call last):
  File "/Users/.../homebrew/Cellar/s3cmd/2.0.1/libexec/bin/s3cmd", line 3073, in <module>
    rc = main()
  File "/Users/.../homebrew/Cellar/s3cmd/2.0.1/libexec/bin/s3cmd", line 2989, in main
    rc = cmd_func(args)
  File "/Users/.../homebrew/Cellar/s3cmd/2.0.1/libexec/bin/s3cmd", line 939, in cmd_info
    expiration_desc += "objects with key prefix '" + expiration['prefix'] + "' "
TypeError: cannot concatenate 'str' and 'NoneType' objects
...
```

**Comment by denis-yuen** [comment] 2018-04-02 18:47
FYI, looks like we're using 
```
Ceph Jewel
radosgw is 10.2.7-1xenial
```

**Comment by garyluu** [comment] 2018-04-04 14:04
@keiranmraine https://github.com/dockstore/s3cmd-plugin/releases/tag/dockstore-file-s3cmd-plugin-0.0.8 was released a while ago with functionality to alter to verbosity.  It should circumvent the issue with `s3cmd info` returning errors with your combination of s3cmd and s3.  Sadly, I cannot reproduce the error on my end.  
`s3cmd info` returns
```
s3://clientbucket/ (bucket):
   Location:  us-east-1
   Payer:     None
   Expiration Rule: none
   policy:  ...
   cors: ...
```
for cancercollaboratory.

For aws, it returns:
```
s3cmd info s3://dockstore.temp
s3://dockstore.temp/ (bucket):
   Location:  us-west-2
   Payer:     BucketOwner
   Expiration Rule: none
   Policy:    none
   CORS:      none
   ACL:       ...
```
Additionally, Cancer collaboratory also stopped supporting s3cmd for a variety of functions since I last tested.  I've been using localstack and aws for tests.

**Comment by denis-yuen** [comment] 2018-08-28 15:58
Closing issue for now, feel free to re-open if this is still a live issue

**Closed** 2018-08-28 15:58 UTC
