### ISSUE TITLE
CWL Secondary Files import not working for ../

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1850] opened 2018-10-01 17:34 UTC
If you have a primary descriptor in one folder, and then the secondary file is defined as something like ../another-folder/importedfile.cwl then we cannot find the secondary file due to some weird relative import issue.

**Comment by denis-yuen** [comment] 2018-10-01 17:45
Looks like some form of regression. 
Can test by forking https://dockstore.org/workflows/github.com/NCI-GDC/gdc-dnaseq-cwl/GDC_DNASeq:master?tab=info and then refreshing

**Comment by agduncan94** [comment] 2018-10-30 14:05
Two related issues here:
1) Github does not understand relative paths
1) Our recursive parsing code does not properly set the initial working dir

It is likely that WDL and nextflow would have this same issue.

**Comment by denis-yuen** [comment] 2018-11-29 19:35
This seems fixed in 1.5.2 at https://staging.dockstore.org/my-workflows/github.com/denis-yuen/gdc-dnaseq-cwl

**Closed** 2018-11-29 19:44 UTC
Labels: bug, web service
