### ISSUE TITLE
Tool/workflow --help message autogenerated

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#270] opened 2016-06-13 00:06 UTC
This can apply to both the website and the command line tool.  It would be very nice to autogenerate a usage message, similar to what a lot of Linux tools do when you pass them a --help.  This could be displayed on the dockstore command line along with a new tab in the Dockstore website.  It would give people more motivation to package tools for Dockstore since they don't have to code this up in their own tools since it provided when using CWL/WDL.

**Comment by denis-yuen** [comment] 2016-06-13 14:17
Related to #22 and #248

**Comment by denis-yuen** [comment] 2016-06-16 14:57
@briandoconnor could you elaborate on this actually?
Presumably this would not display something like `dockstore tool launch --json testArrayHttpInputLocalOutput.json --entry example-org/example-tool `

Were you thinking something like `cwltool --non-strict --enable-net --outdir example-out-dir arrays.cwl workflow_params.json`  ? Or is this actually a duplicate of #248 in that you want to display a command for cwl-runner with a remote descriptor?

**Comment by denis-yuen** [comment] 2016-11-23 22:05
Mutating this, I think this needs two part
1) A way to take in parameters (whether in a json or not) on the command-line, like
```
dockstore tool launch --entry example-org/example-tool  -- --param1 one --param2 two --param3 three
```
or
```
dockstore tool launch --entry example-org/example-tool  --tool-vars '{"param1":"one","param2":"two"}'
```

2) A help function that can display usage information 

```
$ dockstore tool launch --entry example-org/example-tool --help
HELP FOR example-org/example-tool via DOCKSTORE
------------------
See https://www.dockstore.org for more information

Usage: dockstore tool launch --entry example-org/example-tool --help
       dockstore tool launch --entry example-org/example-tool -- [parameters]

Description:
  Launch a example-org/example-tool  locally.

Required parameters:
  --param1 <val>                     Doc from CWL file

Optional parameters:
  --param2 <val>                     Doc from CWL file

------------------
```

**Comment by denis-yuen** [comment] 2017-04-07 20:06
@briandoconnor  Needs elaboration, closing till we get more info

**Closed by denis-yuen** 2017-04-07 20:06 UTC
Labels: enhancement, gui
