### ISSUE TITLE
Unclear message when attempting to link quay.io without logging into quay.io beforehand

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#418] opened 2016-09-16 18:48 UTC
If you have an existing account on dockstore and do the following, you will get an error in Chrome and Safari.
-delete the Quay token from the tokens page
-delete dockstore from authorized applications on quay
-then try and link quay account from dockstore site
-should get the following error
"The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. bad password), or your browser doesn't understand how to supply the credentials required"

This error does not happen on firefox.

**Comment by agduncan94** [comment] 2016-09-16 18:57
This happens if you are not signed into a quay account in the same browser.

**Comment by denis-yuen** [comment] 2016-09-16 19:06
Duplicate of #304  , kinda meant that we should document the workaround

**Comment by denis-yuen** [comment] 2017-04-07 20:10
This seems fixed on the quay.io side. 
Quay.io will now prompt the user to login and after logging in will proceed to the oauth authorization screen.

**Closed by denis-yuen** 2017-04-07 20:10 UTC
Labels: bug
