### ISSUE TITLE
OpenJDK 10

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#561] opened 2016-12-22 17:06 UTC
### Desired behaviour

We should start replacing Oracle JDK 8 with OpenJDK 10. 
This will affect local builds and Travis-CI. 

Partial dependency on Cromwell , how well does this work with 10?)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-169)
┆Issue Type: Story
┆Issue Number: DOCK-169

**Comment by garyluu** [comment] 2018-09-04 18:26
Didn't really look into it much, but tooltester/jenkins didn't seem to work with OpenJDK 10 without changes

**Comment by denis-yuen** [comment] 2018-09-04 18:34
I definitely expect changes for these open-ended tasks :)

**Comment by NatalieEO** [comment] 2019-04-01 17:06
duplicate of ga4gh/dockstore#2320

**Closed by NatalieEO** 2019-04-01 17:06 UTC
Labels: enhancement
